// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rate$0 from "../../../../../golang.org/x/time/rate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Options tunes a background account sync loop.
 */
export class Options {
    /**
     * Creates a new Options instance.
     * @param {Partial<Options>} [$$source = {}] - The source object to create the Options.
     */
    constructor($$source = {}) {
        if (!("PollInterval" in $$source)) {
            /**
             * PollInterval is how often to pull mail forward when no push hint arrives.
             * @member
             * @type {time$0.Duration}
             */
            this["PollInterval"] = time$0.Duration.$zero;
        }
        if (!("BackfillPageSize" in $$source)) {
            /**
             * BackfillPageSize is the envelope page size for history paging.
             * @member
             * @type {number}
             */
            this["BackfillPageSize"] = 0;
        }
        if (!("OutboxInterval" in $$source)) {
            /**
             * OutboxInterval is how often to drain queued outbound sends.
             * @member
             * @type {time$0.Duration}
             */
            this["OutboxInterval"] = time$0.Duration.$zero;
        }
        if (!("SnoozeInterval" in $$source)) {
            /**
             * SnoozeInterval is how often to check for elapsed snoozes.
             * @member
             * @type {time$0.Duration}
             */
            this["SnoozeInterval"] = time$0.Duration.$zero;
        }
        if (!("Rate" in $$source)) {
            /**
             * Rate caps provider requests/sec; Burst is the bucket size. Zero Rate
             * means unlimited.
             * @member
             * @type {rate$0.Limit}
             */
            this["Rate"] = rate$0.Limit.$zero;
        }
        if (!("Burst" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Burst"] = 0;
        }
        if (!("Logger" in $$source)) {
            /**
             * Logger receives progress/error events; defaults to slog.Default().
             * @member
             * @type {slog$0.Logger | null}
             */
            this["Logger"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Options}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Logger" in $$parsedSource) {
            $$parsedSource["Logger"] = $$createField6_0($$parsedSource["Logger"]);
        }
        return new Options(/** @type {Partial<Options>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = slog$0.Logger.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
