// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Prefs controls which new mail raises a desktop notification.
 */
export class Prefs {
    /**
     * Mode is "all", "inbox" (only the inbox), or "none" (suppress entirely).
     */
    "Mode": string;

    /**
     * MutedSenders are addresses ("a@x.io") or domains ("x.io") whose mail never
     * notifies. Matched case-insensitively.
     */
    "MutedSenders": string[];

    /**
     * QuietHours suppresses notifications within a daily window (local time,
     * "HH:MM"), wrapping past midnight when From > To.
     */
    "QuietEnabled": boolean;
    "QuietFrom": string;
    "QuietTo": string;

    /** Creates a new Prefs instance. */
    constructor($$source: Partial<Prefs> = {}) {
        if (!("Mode" in $$source)) {
            this["Mode"] = "";
        }
        if (!("MutedSenders" in $$source)) {
            this["MutedSenders"] = [];
        }
        if (!("QuietEnabled" in $$source)) {
            this["QuietEnabled"] = false;
        }
        if (!("QuietFrom" in $$source)) {
            this["QuietFrom"] = "";
        }
        if (!("QuietTo" in $$source)) {
            this["QuietTo"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Prefs instance from a string or object.
     */
    static createFrom($$source: any = {}): Prefs {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("MutedSenders" in $$parsedSource) {
            $$parsedSource["MutedSenders"] = $$createField1_0($$parsedSource["MutedSenders"]);
        }
        return new Prefs($$parsedSource as Partial<Prefs>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
