// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as Client from "./client.js";
export {
    Client
};

export {
    Account,
    Draft,
    Mailbox,
    Message,
    Outgoing,
    Part,
    Session,
    Snoozed,
    SyncOptions,
    Thread,
    ThreadListItem
} from "./models.js";

import * as $models from "./models.js";

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {$models.AccountID} AccountID
 */

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {$models.LabelID} LabelID
 */

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {$models.MessageID} MessageID
 */

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {$models.ThreadID} ThreadID
 */
