// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../../internal/sync/models.js";

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Account = model$0.Account;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Account} Account
 */

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.AccountID} AccountID
 */

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Draft = model$0.Draft;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Draft} Draft
 */

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.LabelID} LabelID
 */

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Mailbox = model$0.Mailbox;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Mailbox} Mailbox
 */

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Message = model$0.Message;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Message} Message
 */

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.MessageID} MessageID
 */

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Outgoing = model$0.Outgoing;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Outgoing} Outgoing
 */

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Part = model$0.Part;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Part} Part
 */

/**
 * Session binds a Client to a single Account so callers don't repeat the
 * account on every call. It is a thin convenience wrapper; the underlying
 * Client is shared and safe for concurrent use across sessions.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Snoozed = model$0.Snoozed;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Snoozed} Snoozed
 */

/**
 * SyncOptions configures a background sync loop. See sync.Options.
 */
export const SyncOptions = sync$0.Options;

/**
 * SyncOptions configures a background sync loop. See sync.Options.
 * @typedef {sync$0.Options} SyncOptions
 */

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const Thread = model$0.Thread;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.Thread} Thread
 */

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.ThreadID} ThreadID
 */

/**
 * Re-exported domain types so callers depend only on this package.
 */
export const ThreadListItem = model$0.ThreadListItem;

/**
 * Re-exported domain types so callers depend only on this package.
 * @typedef {model$0.ThreadListItem} ThreadListItem
 */
