// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as rate$0 from "../../../../../golang.org/x/time/rate/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slog$0 from "../../../../../log/slog/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Options tunes a background account sync loop.
 */
export class Options {
    /**
     * PollInterval is how often to pull mail forward when no push hint arrives.
     */
    "PollInterval": time$0.Duration;

    /**
     * BackfillPageSize is the envelope page size for history paging.
     */
    "BackfillPageSize": number;

    /**
     * BackfillMaxPages caps background history pages per mailbox. Zero means
     * unlimited, preserving full-backfill behavior for daemon/CLI callers.
     */
    "BackfillMaxPages": number;

    /**
     * OutboxInterval is how often to drain queued outbound sends.
     */
    "OutboxInterval": time$0.Duration;

    /**
     * SnoozeInterval is how often to check for elapsed snoozes.
     */
    "SnoozeInterval": time$0.Duration;

    /**
     * Rate caps provider requests/sec; Burst is the bucket size. Zero Rate
     * means unlimited.
     */
    "Rate": rate$0.Limit;
    "Burst": number;

    /**
     * Logger receives progress/error events; defaults to slog.Default().
     */
    "Logger": slog$0.Logger | null;

    /** Creates a new Options instance. */
    constructor($$source: Partial<Options> = {}) {
        if (!("PollInterval" in $$source)) {
            this["PollInterval"] = time$0.Duration.$zero;
        }
        if (!("BackfillPageSize" in $$source)) {
            this["BackfillPageSize"] = 0;
        }
        if (!("BackfillMaxPages" in $$source)) {
            this["BackfillMaxPages"] = 0;
        }
        if (!("OutboxInterval" in $$source)) {
            this["OutboxInterval"] = time$0.Duration.$zero;
        }
        if (!("SnoozeInterval" in $$source)) {
            this["SnoozeInterval"] = time$0.Duration.$zero;
        }
        if (!("Rate" in $$source)) {
            this["Rate"] = rate$0.Limit.$zero;
        }
        if (!("Burst" in $$source)) {
            this["Burst"] = 0;
        }
        if (!("Logger" in $$source)) {
            this["Logger"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Options instance from a string or object.
     */
    static createFrom($$source: any = {}): Options {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Logger" in $$parsedSource) {
            $$parsedSource["Logger"] = $$createField7_0($$parsedSource["Logger"]);
        }
        return new Options($$parsedSource as Partial<Options>);
    }
}

// Private type creation functions
const $$createType0 = slog$0.Logger.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
