// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Account,
    Address,
    Category,
    Contact,
    Draft,
    Flag,
    Kind,
    Mailbox,
    Message,
    Outfile,
    Outgoing,
    Part,
    Role,
    Snoozed,
    Thread,
    ThreadListItem
} from "./models.js";

export type {
    AccountID,
    LabelID,
    MessageID,
    ThreadID
} from "./models.js";
