// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Account is a configured mailbox login.
 */
export class Account {
    "ID": AccountID;
    "Kind": Kind;
    "Email": string;
    "Name": string;

    /**
     * Connection details for custom IMAP/SMTP accounts. Empty for Gmail and
     * well-known domains, which are resolved from a built-in endpoint map.
     * Credentials live in auth.CredentialStore, never here.
     */
    "IMAPHost": string;
    "IMAPPort": number;
    "SMTPHost": string;
    "SMTPPort": number;

    /** Creates a new Account instance. */
    constructor($$source: Partial<Account> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = Kind.$zero;
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("IMAPHost" in $$source)) {
            this["IMAPHost"] = "";
        }
        if (!("IMAPPort" in $$source)) {
            this["IMAPPort"] = 0;
        }
        if (!("SMTPHost" in $$source)) {
            this["SMTPHost"] = "";
        }
        if (!("SMTPPort" in $$source)) {
            this["SMTPPort"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     */
    static createFrom($$source: any = {}): Account {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account($$parsedSource as Partial<Account>);
    }
}

/**
 * AccountID identifies a configured account in the local store.
 */
export type AccountID = string;

/**
 * Address is a parsed RFC 5322 address.
 */
export class Address {
    "Name": string;
    "Addr": string;

    /** Creates a new Address instance. */
    constructor($$source: Partial<Address> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Addr" in $$source)) {
            this["Addr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Address instance from a string or object.
     */
    static createFrom($$source: any = {}): Address {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Address($$parsedSource as Partial<Address>);
    }
}

/**
 * Category is the app-level inbox grouping used for Gmail-like sections.
 */
export enum Category {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CategoryPrimary = "primary",
    CategoryPromotions = "promotions",
    CategoryUpdates = "updates",
    CategorySocial = "social",
    CategoryForums = "forums",
};

/**
 * Draft is a locally-saved, autosaved compose draft.
 */
export class Draft {
    "ID": string;
    "Account": AccountID;
    "Message": Outgoing;
    "Updated": time$0.Time;

    /** Creates a new Draft instance. */
    constructor($$source: Partial<Draft> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            this["Account"] = "";
        }
        if (!("Message" in $$source)) {
            this["Message"] = (new Outgoing());
        }
        if (!("Updated" in $$source)) {
            this["Updated"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Draft instance from a string or object.
     */
    static createFrom($$source: any = {}): Draft {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Message" in $$parsedSource) {
            $$parsedSource["Message"] = $$createField2_0($$parsedSource["Message"]);
        }
        return new Draft($$parsedSource as Partial<Draft>);
    }
}

/**
 * Flag is a per-message state bit (seen, flagged, answered, draft, ...).
 */
export enum Flag {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FlagSeen = "\\Seen",
    FlagFlagged = "\\Flagged",
    FlagAnswered = "\\Answered",
    FlagDraft = "\\Draft",
    FlagDeleted = "\\Deleted",
};

/**
 * Kind distinguishes the backend used by an account.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    KindIMAP = 0,
    KindGmail = 1,
};

/**
 * LabelID identifies a Gmail label or, for IMAP, a folder mapped to a label.
 */
export type LabelID = string;

/**
 * Mailbox is an IMAP folder or a Gmail label, normalized.
 */
export class Mailbox {
    "ID": LabelID;
    "Account": AccountID;

    /**
     * display name
     */
    "Name": string;

    /**
     * IMAP folder path; empty for Gmail
     */
    "Path": string;

    /**
     * semantic role if known (Inbox, Sent, ...)
     */
    "Role": Role;
    "Unread": number;
    "Total": number;

    /** Creates a new Mailbox instance. */
    constructor($$source: Partial<Mailbox> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            this["Account"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Path" in $$source)) {
            this["Path"] = "";
        }
        if (!("Role" in $$source)) {
            this["Role"] = Role.$zero;
        }
        if (!("Unread" in $$source)) {
            this["Unread"] = 0;
        }
        if (!("Total" in $$source)) {
            this["Total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mailbox instance from a string or object.
     */
    static createFrom($$source: any = {}): Mailbox {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mailbox($$parsedSource as Partial<Mailbox>);
    }
}

/**
 * Message is the envelope + metadata. Body parts are loaded lazily.
 */
export class Message {
    "ID": MessageID;
    "Thread": ThreadID;
    "Account": AccountID;
    "Subject": string;
    "From": Address[];
    "To": Address[];
    "Cc": Address[];
    "Bcc": Address[];
    "Date": time$0.Time;
    "Snippet": string;
    "Category": Category;
    "Flags": Flag[];
    "Labels": LabelID[];
    "HasAttachments": boolean;

    /**
     * RFCMessageID is the RFC 5322 Message-ID header; References is the chain.
     * Used to construct correct reply/forward threading.
     */
    "RFCMessageID": string;
    "References": string[];

    /**
     * BodyLoaded reports whether Parts are populated in the store.
     */
    "BodyLoaded": boolean;
    "Parts": Part[];

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Thread" in $$source)) {
            this["Thread"] = "";
        }
        if (!("Account" in $$source)) {
            this["Account"] = "";
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("From" in $$source)) {
            this["From"] = [];
        }
        if (!("To" in $$source)) {
            this["To"] = [];
        }
        if (!("Cc" in $$source)) {
            this["Cc"] = [];
        }
        if (!("Bcc" in $$source)) {
            this["Bcc"] = [];
        }
        if (!("Date" in $$source)) {
            this["Date"] = null;
        }
        if (!("Snippet" in $$source)) {
            this["Snippet"] = "";
        }
        if (!("Category" in $$source)) {
            this["Category"] = Category.$zero;
        }
        if (!("Flags" in $$source)) {
            this["Flags"] = [];
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = [];
        }
        if (!("HasAttachments" in $$source)) {
            this["HasAttachments"] = false;
        }
        if (!("RFCMessageID" in $$source)) {
            this["RFCMessageID"] = "";
        }
        if (!("References" in $$source)) {
            this["References"] = [];
        }
        if (!("BodyLoaded" in $$source)) {
            this["BodyLoaded"] = false;
        }
        if (!("Parts" in $$source)) {
            this["Parts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType4;
        const $$createField15_0 = $$createType5;
        const $$createField17_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("From" in $$parsedSource) {
            $$parsedSource["From"] = $$createField4_0($$parsedSource["From"]);
        }
        if ("To" in $$parsedSource) {
            $$parsedSource["To"] = $$createField5_0($$parsedSource["To"]);
        }
        if ("Cc" in $$parsedSource) {
            $$parsedSource["Cc"] = $$createField6_0($$parsedSource["Cc"]);
        }
        if ("Bcc" in $$parsedSource) {
            $$parsedSource["Bcc"] = $$createField7_0($$parsedSource["Bcc"]);
        }
        if ("Flags" in $$parsedSource) {
            $$parsedSource["Flags"] = $$createField11_0($$parsedSource["Flags"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField12_0($$parsedSource["Labels"]);
        }
        if ("References" in $$parsedSource) {
            $$parsedSource["References"] = $$createField15_0($$parsedSource["References"]);
        }
        if ("Parts" in $$parsedSource) {
            $$parsedSource["Parts"] = $$createField17_0($$parsedSource["Parts"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * MessageID is the SDK-internal stable id for a message (typically the
 * RFC 5322 Message-ID, falling back to a synthesized id).
 */
export type MessageID = string;

/**
 * Outfile is an attachment to include in an Outgoing message.
 */
export class Outfile {
    "Filename": string;
    "ContentType": string;
    "Content": string;

    /** Creates a new Outfile instance. */
    constructor($$source: Partial<Outfile> = {}) {
        if (!("Filename" in $$source)) {
            this["Filename"] = "";
        }
        if (!("ContentType" in $$source)) {
            this["ContentType"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Outfile instance from a string or object.
     */
    static createFrom($$source: any = {}): Outfile {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Content" in $$parsedSource) {
            $$parsedSource["Content"] = $$createField2_0($$parsedSource["Content"]);
        }
        return new Outfile($$parsedSource as Partial<Outfile>);
    }
}

/**
 * Outgoing is a message to be composed and sent.
 */
export class Outgoing {
    "From": Address;
    "To": Address[];
    "Cc": Address[];
    "Bcc": Address[];
    "Subject": string;

    /**
     * text/plain body
     */
    "Text": string;

    /**
     * optional text/html alternative
     */
    "HTML": string;

    /**
     * Threading: when replying, set InReplyTo to the parent's Message-ID and
     * References to the full chain so clients thread the reply correctly.
     */
    "InReplyTo": string;
    "References": string[];

    /**
     * Thread, if set, attaches the message to an existing provider thread.
     */
    "Thread": ThreadID;
    "Attachments": Outfile[];

    /** Creates a new Outgoing instance. */
    constructor($$source: Partial<Outgoing> = {}) {
        if (!("From" in $$source)) {
            this["From"] = (new Address());
        }
        if (!("To" in $$source)) {
            this["To"] = [];
        }
        if (!("Cc" in $$source)) {
            this["Cc"] = [];
        }
        if (!("Bcc" in $$source)) {
            this["Bcc"] = [];
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("HTML" in $$source)) {
            this["HTML"] = "";
        }
        if (!("InReplyTo" in $$source)) {
            this["InReplyTo"] = "";
        }
        if (!("References" in $$source)) {
            this["References"] = [];
        }
        if (!("Thread" in $$source)) {
            this["Thread"] = "";
        }
        if (!("Attachments" in $$source)) {
            this["Attachments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Outgoing instance from a string or object.
     */
    static createFrom($$source: any = {}): Outgoing {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField8_0 = $$createType5;
        const $$createField10_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("From" in $$parsedSource) {
            $$parsedSource["From"] = $$createField0_0($$parsedSource["From"]);
        }
        if ("To" in $$parsedSource) {
            $$parsedSource["To"] = $$createField1_0($$parsedSource["To"]);
        }
        if ("Cc" in $$parsedSource) {
            $$parsedSource["Cc"] = $$createField2_0($$parsedSource["Cc"]);
        }
        if ("Bcc" in $$parsedSource) {
            $$parsedSource["Bcc"] = $$createField3_0($$parsedSource["Bcc"]);
        }
        if ("References" in $$parsedSource) {
            $$parsedSource["References"] = $$createField8_0($$parsedSource["References"]);
        }
        if ("Attachments" in $$parsedSource) {
            $$parsedSource["Attachments"] = $$createField10_0($$parsedSource["Attachments"]);
        }
        return new Outgoing($$parsedSource as Partial<Outgoing>);
    }
}

/**
 * Part is a single MIME part of a message body.
 */
export class Part {
    "ContentType": string;
    "Charset": string;

    /**
     * inline | attachment
     */
    "Disposition": string;
    "Filename": string;
    "Size": number;

    /**
     * Content is populated only when loaded; large attachments are spooled to
     * the blob store and referenced by BlobRef instead.
     */
    "Content": string;
    "BlobRef": string;

    /** Creates a new Part instance. */
    constructor($$source: Partial<Part> = {}) {
        if (!("ContentType" in $$source)) {
            this["ContentType"] = "";
        }
        if (!("Charset" in $$source)) {
            this["Charset"] = "";
        }
        if (!("Disposition" in $$source)) {
            this["Disposition"] = "";
        }
        if (!("Filename" in $$source)) {
            this["Filename"] = "";
        }
        if (!("Size" in $$source)) {
            this["Size"] = 0;
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("BlobRef" in $$source)) {
            this["BlobRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Part instance from a string or object.
     */
    static createFrom($$source: any = {}): Part {
        const $$createField5_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Content" in $$parsedSource) {
            $$parsedSource["Content"] = $$createField5_0($$parsedSource["Content"]);
        }
        return new Part($$parsedSource as Partial<Part>);
    }
}

/**
 * Role tags well-known mailboxes so the UI can find them across providers.
 */
export enum Role {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    RoleNone = 0,
    RoleInbox = 1,
    RoleSent = 2,
    RoleDrafts = 3,
    RoleTrash = 4,
    RoleSpam = 5,
    RoleArchive = 6,
};

/**
 * Snoozed records a message hidden from the inbox until Until.
 */
export class Snoozed {
    "Message": MessageID;
    "Until": time$0.Time;

    /** Creates a new Snoozed instance. */
    constructor($$source: Partial<Snoozed> = {}) {
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Until" in $$source)) {
            this["Until"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snoozed instance from a string or object.
     */
    static createFrom($$source: any = {}): Snoozed {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snoozed($$parsedSource as Partial<Snoozed>);
    }
}

/**
 * Thread is a conversation grouping.
 */
export class Thread {
    "ID": ThreadID;
    "Account": AccountID;
    "Subject": string;
    "Messages": MessageID[];
    "Last": time$0.Time;
    "Unread": boolean;

    /** Creates a new Thread instance. */
    constructor($$source: Partial<Thread> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            this["Account"] = "";
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("Messages" in $$source)) {
            this["Messages"] = [];
        }
        if (!("Last" in $$source)) {
            this["Last"] = null;
        }
        if (!("Unread" in $$source)) {
            this["Unread"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thread instance from a string or object.
     */
    static createFrom($$source: any = {}): Thread {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Messages" in $$parsedSource) {
            $$parsedSource["Messages"] = $$createField3_0($$parsedSource["Messages"]);
        }
        return new Thread($$parsedSource as Partial<Thread>);
    }
}

/**
 * ThreadID groups messages into a conversation.
 */
export type ThreadID = string;

/**
 * ThreadListItem is a denormalized conversation-list row, purpose-built for a
 * UI inbox view: everything needed to render one row without loading messages.
 */
export class ThreadListItem {
    "ID": ThreadID;
    "Account": AccountID;
    "Subject": string;
    "Last": time$0.Time;
    "Unread": boolean;

    /**
     * messages in the thread
     */
    "Count": number;

    /**
     * From of the newest message
     */
    "LatestSender": Address;

    /**
     * distinct senders across the thread, oldest first
     */
    "Participants": Address[];

    /**
     * newest message's snippet
     */
    "Snippet": string;

    /**
     * newest message category
     */
    "Category": Category;
    "HasAttachments": boolean;

    /**
     * union of labels across the thread
     */
    "Labels": LabelID[];

    /** Creates a new ThreadListItem instance. */
    constructor($$source: Partial<ThreadListItem> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            this["Account"] = "";
        }
        if (!("Subject" in $$source)) {
            this["Subject"] = "";
        }
        if (!("Last" in $$source)) {
            this["Last"] = null;
        }
        if (!("Unread" in $$source)) {
            this["Unread"] = false;
        }
        if (!("Count" in $$source)) {
            this["Count"] = 0;
        }
        if (!("LatestSender" in $$source)) {
            this["LatestSender"] = (new Address());
        }
        if (!("Participants" in $$source)) {
            this["Participants"] = [];
        }
        if (!("Snippet" in $$source)) {
            this["Snippet"] = "";
        }
        if (!("Category" in $$source)) {
            this["Category"] = Category.$zero;
        }
        if (!("HasAttachments" in $$source)) {
            this["HasAttachments"] = false;
        }
        if (!("Labels" in $$source)) {
            this["Labels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreadListItem {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        const $$createField11_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LatestSender" in $$parsedSource) {
            $$parsedSource["LatestSender"] = $$createField6_0($$parsedSource["LatestSender"]);
        }
        if ("Participants" in $$parsedSource) {
            $$parsedSource["Participants"] = $$createField7_0($$parsedSource["Participants"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField11_0($$parsedSource["Labels"]);
        }
        return new ThreadListItem($$parsedSource as Partial<ThreadListItem>);
    }
}

// Private type creation functions
const $$createType0 = Outgoing.createFrom;
const $$createType1 = Address.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = Part.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Outfile.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
