// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Limit defines the maximum frequency of some events.
 * Limit is represented as number of events per second.
 * A zero Limit allows no events.
 */
export enum Limit {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * Inf is the infinite rate limit; it allows all events (even if burst is zero).
     */
    Inf = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,
};
