// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Client is the SDK entry point. Safe for concurrent use.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../../internal/sync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Accounts lists configured accounts.
 */
export function Accounts(): $CancellablePromise<$models.Account[]> {
    return $Call.ByID(1888665650).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddAccount registers an account and its mailbox topology, then returns the
 * mailboxes. Call StartSync to begin pulling mail.
 */
export function AddAccount(acct: $models.Account): $CancellablePromise<$models.Mailbox[]> {
    return $Call.ByID(1547130912, acct).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ApplyLabels adds and/or removes labels on messages.
 */
export function ApplyLabels(acct: $models.Account, ids: $models.MessageID[], add: $models.LabelID[], remove: $models.LabelID[]): $CancellablePromise<void> {
    return $Call.ByID(3220980065, acct, ids, add, remove);
}

/**
 * Archive ("Done") removes messages from the inbox and records completion for
 * the Done-today metric.
 */
export function Archive(acct: $models.Account, ids: $models.MessageID[]): $CancellablePromise<void> {
    return $Call.ByID(1491701216, acct, ids);
}

/**
 * Attachments returns just the attachment parts of a message (loading the body
 * if needed).
 */
export function Attachments(acct: $models.Account, id: $models.MessageID): $CancellablePromise<$models.Part[]> {
    return $Call.ByID(4193671900, acct, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Close stops all sync loops, closes providers, and closes the store.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(490300998);
}

/**
 * ConversationList returns denormalized conversation-list rows (participants,
 * snippet, count, latest sender, labels) ready to render an inbox view.
 */
export function ConversationList(acct: $models.AccountID, limit: number): $CancellablePromise<$models.ThreadListItem[]> {
    return $Call.ByID(1627871013, acct, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Delete moves messages to Trash.
 */
export function Delete(acct: $models.Account, ids: $models.MessageID[]): $CancellablePromise<void> {
    return $Call.ByID(2393304069, acct, ids);
}

/**
 * DiscardDraft deletes a draft.
 */
export function DiscardDraft(acct: $models.AccountID, id: string): $CancellablePromise<void> {
    return $Call.ByID(1216014991, acct, id);
}

/**
 * DoneToday counts messages archived ("done") since local midnight.
 */
export function DoneToday(acct: $models.AccountID): $CancellablePromise<number> {
    return $Call.ByID(1307604307, acct);
}

/**
 * Draft returns a single draft.
 */
export function Draft(acct: $models.AccountID, id: string): $CancellablePromise<$models.Draft> {
    return $Call.ByID(3571632681, acct, id).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Drafts lists an account's drafts, most recently updated first.
 */
export function Drafts(acct: $models.AccountID): $CancellablePromise<$models.Draft[]> {
    return $Call.ByID(2063895470, acct).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * Events returns a changefeed channel of store mutations and a cancel func.
 * Events are hints — coalesce and refetch rather than treating them as a log.
 */
export function Events(): $CancellablePromise<[any, any]> {
    return $Call.ByID(1989757215);
}

/**
 * ForgetAccount stops the account's sync loop, closes its provider, removes it
 * from the local store (mailboxes/messages cascade), and drops the cached
 * provider. Credentials live outside the store and must be deleted by the
 * caller. Safe to call for an account that was never fully registered.
 */
export function ForgetAccount(acct: $models.AccountID): $CancellablePromise<void> {
    return $Call.ByID(588609534, acct);
}

/**
 * MailboxMessages returns messages in a mailbox/label, newest first.
 */
export function MailboxMessages(acct: $models.AccountID, mailbox: $models.LabelID, limit: number): $CancellablePromise<$models.Message[]> {
    return $Call.ByID(3021781842, acct, mailbox, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Mailboxes returns the mailbox/label topology for an account.
 */
export function Mailboxes(acct: $models.AccountID): $CancellablePromise<$models.Mailbox[]> {
    return $Call.ByID(2122000366, acct).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * MarkRead marks messages read (read=true) or unread (read=false).
 */
export function MarkRead(acct: $models.Account, ids: $models.MessageID[], read: boolean): $CancellablePromise<void> {
    return $Call.ByID(2589818727, acct, ids, read);
}

/**
 * Message returns a single message envelope from the local store.
 */
export function Message(acct: $models.AccountID, id: $models.MessageID): $CancellablePromise<$models.Message> {
    return $Call.ByID(2412445921, acct, id).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * MessageBody returns a message's decoded parts (inline bodies + attachments).
 * The first call fetches from the provider, parses the MIME, persists the parts,
 * and makes the body searchable; subsequent calls are served from the local
 * store with no network.
 */
export function MessageBody(acct: $models.Account, id: $models.MessageID): $CancellablePromise<$models.Part[]> {
    return $Call.ByID(405842225, acct, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Move relocates messages to a destination mailbox/label.
 */
export function Move(acct: $models.Account, ids: $models.MessageID[], dst: $models.LabelID): $CancellablePromise<void> {
    return $Call.ByID(1572771159, acct, ids, dst);
}

/**
 * PreloadMailboxBodies fetches and caches bodies for the newest messages in a
 * mailbox. It is intended for opportunistic UI prewarming after a list view has
 * rendered; already-loaded bodies are skipped.
 */
export function PreloadMailboxBodies(acct: $models.Account, mailbox: $models.LabelID, limit: number): $CancellablePromise<number> {
    return $Call.ByID(1232022425, acct, mailbox, limit);
}

/**
 * ReclassifyMailbox recalculates Gmail-like categories for recent messages in a
 * mailbox, using any cached body text as extra signal.
 */
export function ReclassifyMailbox(acct: $models.AccountID, mailbox: $models.LabelID, limit: number): $CancellablePromise<number> {
    return $Call.ByID(2889393319, acct, mailbox, limit);
}

/**
 * SaveDraft upserts a compose draft locally and returns its id (generated if
 * empty). Cheap — safe to call on every keystroke for autosave.
 */
export function SaveDraft(acct: $models.AccountID, id: string, out: $models.Outgoing): $CancellablePromise<string> {
    return $Call.ByID(814302978, acct, id, out);
}

/**
 * Search runs a local full-text query (subject/sender; body once body-sync
 * lands), newest first.
 */
export function Search(acct: $models.AccountID, query: string, limit: number): $CancellablePromise<$models.Message[]> {
    return $Call.ByID(3928586418, acct, query, limit).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Send composes, queues, and immediately delivers a message. On delivery
 * failure it remains in the durable outbox for retry (e.g. by a running sync
 * loop). Returns true if it went out now.
 */
export function Send(acct: $models.Account, out: $models.Outgoing): $CancellablePromise<boolean> {
    return $Call.ByID(1446605080, acct, out);
}

/**
 * SendDraft sends a saved draft, then discards it on success.
 */
export function SendDraft(acct: $models.Account, id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1628548267, acct, id);
}

/**
 * Session returns a per-account handle. It does not register the account; call
 * Register (or Client.AddAccount) once before syncing.
 */
export function Session(acct: $models.Account): $CancellablePromise<$models.Session | null> {
    return $Call.ByID(2331330750, acct).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * Snooze hides messages from the inbox until `until`; a running sync loop
 * returns them automatically when the time elapses.
 */
export function Snooze(acct: $models.Account, ids: $models.MessageID[], until: time$0.Time): $CancellablePromise<void> {
    return $Call.ByID(4201012976, acct, ids, until);
}

/**
 * Snoozed lists current snoozes for an account.
 */
export function Snoozed(acct: $models.AccountID): $CancellablePromise<$models.Snoozed[]> {
    return $Call.ByID(3274105596, acct).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Star flags/unflags messages.
 */
export function Star(acct: $models.Account, ids: $models.MessageID[], on: boolean): $CancellablePromise<void> {
    return $Call.ByID(2522550274, acct, ids, on);
}

/**
 * StartSync launches the background sync loop for an account (forward poll +
 * IDLE/push where supported, resumable backfill, outbox drain). It returns
 * immediately; call StopSync or Close to stop. Re-calling for the same account
 * replaces the previous loop.
 */
export function StartSync(acct: $models.Account, mailboxes: $models.LabelID[], opts: $models.SyncOptions): $CancellablePromise<void> {
    return $Call.ByID(165761721, acct, mailboxes, opts);
}

/**
 * StopSync stops the background loop for an account, if running.
 */
export function StopSync(acct: $models.AccountID): $CancellablePromise<void> {
    return $Call.ByID(4031201081, acct);
}

/**
 * SyncOnce runs one forward sync of a mailbox (pull new mail into the store).
 */
export function SyncOnce(acct: $models.Account, mailbox: $models.LabelID): $CancellablePromise<number> {
    return $Call.ByID(2978107256, acct, mailbox);
}

/**
 * ThreadMessages returns all messages in a thread, oldest first.
 */
export function ThreadMessages(acct: $models.AccountID, thread: $models.ThreadID): $CancellablePromise<$models.Message[]> {
    return $Call.ByID(2632018090, acct, thread).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Threads lists conversations for an account, newest activity first.
 */
export function Threads(acct: $models.AccountID, limit: number): $CancellablePromise<$models.Thread[]> {
    return $Call.ByID(1929023415, acct, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Unsnooze returns snoozed messages to the inbox immediately.
 */
export function Unsnooze(acct: $models.Account, ids: $models.MessageID[]): $CancellablePromise<void> {
    return $Call.ByID(916971923, acct, ids);
}

// Private type creation functions
const $$createType0 = model$0.Account.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.Mailbox.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.Part.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.ThreadListItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.Draft.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = model$0.Message.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.Session.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = model$0.Snoozed.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = model$0.Thread.createFrom;
const $$createType17 = $Create.Array($$createType16);
