// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Contacts exposes the harvested address book for recipient autocomplete.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as email$0 from "../../email/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * Search returns address-book entries matching query (address or name),
 * ranked by frequency then recency.
 */
export function Search(acct: email$0.AccountID, query: string, limit: number): $CancellablePromise<email$0.Contact[]> {
    return $Call.ByID(1653487975, acct, query, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Contact.createFrom;
const $$createType1 = $Create.Array($$createType0);
