// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Mutations exposes optimistic message state changes (flags, labels, moves).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as email$0 from "../../email/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

export function ApplyLabels(acct: email$0.Account, ids: email$0.MessageID[], add: email$0.LabelID[], remove: email$0.LabelID[]): $CancellablePromise<void> {
    return $Call.ByID(869874707, acct, ids, add, remove);
}

export function Archive(acct: email$0.Account, ids: email$0.MessageID[]): $CancellablePromise<void> {
    return $Call.ByID(1139453646, acct, ids);
}

export function Delete(acct: email$0.Account, ids: email$0.MessageID[]): $CancellablePromise<void> {
    return $Call.ByID(2953001147, acct, ids);
}

export function MarkRead(acct: email$0.Account, ids: email$0.MessageID[], read: boolean): $CancellablePromise<void> {
    return $Call.ByID(781568289, acct, ids, read);
}

export function Move(acct: email$0.Account, ids: email$0.MessageID[], dst: email$0.LabelID): $CancellablePromise<void> {
    return $Call.ByID(3686961005, acct, ids, dst);
}

export function Star(acct: email$0.Account, ids: email$0.MessageID[], on: boolean): $CancellablePromise<void> {
    return $Call.ByID(659581504, acct, ids, on);
}
