// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Compose exposes draft persistence and message delivery.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as email$0 from "../../internal/email/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../internal/model/models.js";

export function DiscardDraft(acct: email$0.AccountID, id: string): $CancellablePromise<void> {
    return $Call.ByID(1995142285, acct, id);
}

export function Draft(acct: email$0.AccountID, id: string): $CancellablePromise<email$0.Draft> {
    return $Call.ByID(2003027279, acct, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Drafts(acct: email$0.AccountID): $CancellablePromise<email$0.Draft[]> {
    return $Call.ByID(772767092, acct).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SaveDraft(acct: email$0.AccountID, id: string, out: email$0.Outgoing): $CancellablePromise<string> {
    return $Call.ByID(4235329584, acct, id, out);
}

export function Send(acct: email$0.Account, out: email$0.Outgoing): $CancellablePromise<boolean> {
    return $Call.ByID(1910189506, acct, out);
}

export function SendDraft(acct: email$0.Account, id: string): $CancellablePromise<boolean> {
    return $Call.ByID(4094153569, acct, id);
}

// Private type creation functions
const $$createType0 = model$0.Draft.createFrom;
const $$createType1 = $Create.Array($$createType0);
