// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Messages exposes read paths plus on-demand and opportunistic fetching.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as email$0 from "../../internal/email/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../internal/model/models.js";

export function Attachments(acct: email$0.Account, id: email$0.MessageID): $CancellablePromise<email$0.Part[]> {
    return $Call.ByID(1751643258, acct, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ConversationList(acct: email$0.AccountID, limit: number): $CancellablePromise<email$0.ThreadListItem[]> {
    return $Call.ByID(2878919967, acct, limit).then(($result: any) => {
        return $$createType3($result);
    });
}

export function MailboxMessages(acct: email$0.AccountID, mailbox: email$0.LabelID, limit: number): $CancellablePromise<email$0.Message[]> {
    return $Call.ByID(3681257412, acct, mailbox, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Message(acct: email$0.AccountID, id: email$0.MessageID): $CancellablePromise<email$0.Message> {
    return $Call.ByID(2913499527, acct, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function MessageBody(acct: email$0.Account, id: email$0.MessageID): $CancellablePromise<email$0.Part[]> {
    return $Call.ByID(62689727, acct, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function PreloadMailboxBodies(acct: email$0.Account, mailbox: email$0.LabelID, limit: number): $CancellablePromise<number> {
    return $Call.ByID(1059989683, acct, mailbox, limit);
}

export function ReclassifyMailbox(acct: email$0.AccountID, mailbox: email$0.LabelID, limit: number): $CancellablePromise<number> {
    return $Call.ByID(799274437, acct, mailbox, limit);
}

export function Search(acct: email$0.AccountID, query: string, limit: number): $CancellablePromise<email$0.Message[]> {
    return $Call.ByID(54108748, acct, query, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SyncOnce populates a never-before-opened folder on demand (forward + backfill).
 */
export function SyncOnce(acct: email$0.Account, mailbox: email$0.LabelID): $CancellablePromise<number> {
    return $Call.ByID(3883702062, acct, mailbox);
}

export function ThreadMessages(acct: email$0.AccountID, thread: email$0.ThreadID): $CancellablePromise<email$0.Message[]> {
    return $Call.ByID(1907660492, acct, thread).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Threads(acct: email$0.AccountID, limit: number): $CancellablePromise<email$0.Thread[]> {
    return $Call.ByID(2158448457, acct, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.Part.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.ThreadListItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.Message.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.Thread.createFrom;
const $$createType7 = $Create.Array($$createType6);
