// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Onboarding is a Wails service for adding, listing, and removing mail
 * accounts. It is the only path that writes credentials; the rest of the app
 * reads them through the provider factory. Register it alongside the email
 * Client so the frontend onboarding flow can call these methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as email$0 from "../../pkg/email/models.js";

/**
 * AddAppPasswordAccount registers an IMAP/SMTP account authenticated with a
 * password or app password (e.g. a Gmail App Password). No OAuth, no browser.
 */
export function AddAppPasswordAccount(emailAddr: string, displayName: string, appPassword: string): $CancellablePromise<email$0.Account> {
    return $Call.ByID(2174294703, emailAddr, displayName, appPassword).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddGoogleAccount registers a Gmail account via the OAuth loopback flow. It
 * opens the system browser for consent and blocks until the user finishes (or
 * ctx is cancelled), then persists the refresh token, registers the account,
 * and starts background sync. emailAddr is the Gmail address being added and
 * doubles as the account id.
 */
export function AddGoogleAccount(emailAddr: string, displayName: string): $CancellablePromise<email$0.Account> {
    return $Call.ByID(1323174484, emailAddr, displayName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListAccounts returns the configured accounts for the settings UI.
 */
export function ListAccounts(): $CancellablePromise<email$0.Account[]> {
    return $Call.ByID(1948771863).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveAccount stops sync, forgets the account's local data, and deletes its
 * stored credential.
 */
export function RemoveAccount(id: email$0.AccountID): $CancellablePromise<void> {
    return $Call.ByID(191899866, id);
}

// Private type creation functions
const $$createType0 = model$0.Account.createFrom;
const $$createType1 = $Create.Array($$createType0);
