// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Snooze exposes snooze scheduling and the Done-today metric.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as email$0 from "../../internal/email/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../internal/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export function DoneToday(acct: email$0.AccountID): $CancellablePromise<number> {
    return $Call.ByID(311847611, acct);
}

export function Snooze(acct: email$0.Account, ids: email$0.MessageID[], until: time$0.Time): $CancellablePromise<void> {
    return $Call.ByID(2138142344, acct, ids, until);
}

export function Snoozed(acct: email$0.AccountID): $CancellablePromise<email$0.Snoozed[]> {
    return $Call.ByID(2342401412, acct).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Unsnooze(acct: email$0.Account, ids: email$0.MessageID[]): $CancellablePromise<void> {
    return $Call.ByID(3898383707, acct, ids);
}

// Private type creation functions
const $$createType0 = model$0.Snoozed.createFrom;
const $$createType1 = $Create.Array($$createType0);
