// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncSettings is the thin Wails service that exposes runtime sync controls to
 * the frontend, keeping App's other methods off the binding surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * PollIntervalSeconds reports the current background poll interval, in seconds.
 */
export function PollIntervalSeconds(): $CancellablePromise<number> {
    return $Call.ByID(2051015435);
}

/**
 * SetPollInterval changes the background poll interval (seconds) and restarts
 * the sync loops. Values below the minimum are clamped server-side.
 */
export function SetPollInterval(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(997998774, seconds);
}
