// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    Account,
    Address,
    Draft,
    Flag,
    Kind,
    Mailbox,
    Message,
    Outfile,
    Outgoing,
    Part,
    Role,
    Snoozed,
    Thread,
    ThreadListItem
} from "./models.js";

import * as $models from "./models.js";

/**
 * AccountID identifies a configured account in the local store.
 * @typedef {$models.AccountID} AccountID
 */

/**
 * LabelID identifies a Gmail label or, for IMAP, a folder mapped to a label.
 * @typedef {$models.LabelID} LabelID
 */

/**
 * MessageID is the SDK-internal stable id for a message (typically the
 * RFC 5322 Message-ID, falling back to a synthesized id).
 * @typedef {$models.MessageID} MessageID
 */

/**
 * ThreadID groups messages into a conversation.
 * @typedef {$models.ThreadID} ThreadID
 */
