// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Account is a configured mailbox login.
 */
export class Account {
    /**
     * Creates a new Account instance.
     * @param {Partial<Account>} [$$source = {}] - The source object to create the Account.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {AccountID}
             */
            this["ID"] = "";
        }
        if (!("Kind" in $$source)) {
            /**
             * @member
             * @type {Kind}
             */
            this["Kind"] = Kind.$zero;
        }
        if (!("Email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Email"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Account instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Account}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Account(/** @type {Partial<Account>} */($$parsedSource));
    }
}

/**
 * AccountID identifies a configured account in the local store.
 * @typedef {string} AccountID
 */

/**
 * Address is a parsed RFC 5322 address.
 */
export class Address {
    /**
     * Creates a new Address instance.
     * @param {Partial<Address>} [$$source = {}] - The source object to create the Address.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Addr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Addr"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Address instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Address}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Address(/** @type {Partial<Address>} */($$parsedSource));
    }
}

/**
 * Draft is a locally-saved, autosaved compose draft.
 */
export class Draft {
    /**
     * Creates a new Draft instance.
     * @param {Partial<Draft>} [$$source = {}] - The source object to create the Draft.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            /**
             * @member
             * @type {AccountID}
             */
            this["Account"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {Outgoing}
             */
            this["Message"] = (new Outgoing());
        }
        if (!("Updated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Updated"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Draft instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Draft}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Message" in $$parsedSource) {
            $$parsedSource["Message"] = $$createField2_0($$parsedSource["Message"]);
        }
        return new Draft(/** @type {Partial<Draft>} */($$parsedSource));
    }
}

/**
 * Flag is a per-message state bit (seen, flagged, answered, draft, ...).
 * @readonly
 * @enum {string}
 */
export const Flag = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FlagSeen: "\\Seen",
    FlagFlagged: "\\Flagged",
    FlagAnswered: "\\Answered",
    FlagDraft: "\\Draft",
    FlagDeleted: "\\Deleted",
};

/**
 * Kind distinguishes the backend used by an account.
 * @readonly
 * @enum {number}
 */
export const Kind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    KindIMAP: 0,
    KindGmail: 1,
};

/**
 * LabelID identifies a Gmail label or, for IMAP, a folder mapped to a label.
 * @typedef {string} LabelID
 */

/**
 * Mailbox is an IMAP folder or a Gmail label, normalized.
 */
export class Mailbox {
    /**
     * Creates a new Mailbox instance.
     * @param {Partial<Mailbox>} [$$source = {}] - The source object to create the Mailbox.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {LabelID}
             */
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            /**
             * @member
             * @type {AccountID}
             */
            this["Account"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * display name
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Path" in $$source)) {
            /**
             * IMAP folder path; empty for Gmail
             * @member
             * @type {string}
             */
            this["Path"] = "";
        }
        if (!("Role" in $$source)) {
            /**
             * semantic role if known (Inbox, Sent, ...)
             * @member
             * @type {Role}
             */
            this["Role"] = Role.$zero;
        }
        if (!("Unread" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Unread"] = 0;
        }
        if (!("Total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mailbox instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Mailbox}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mailbox(/** @type {Partial<Mailbox>} */($$parsedSource));
    }
}

/**
 * Message is the envelope + metadata. Body parts are loaded lazily.
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {MessageID}
             */
            this["ID"] = "";
        }
        if (!("Thread" in $$source)) {
            /**
             * @member
             * @type {ThreadID}
             */
            this["Thread"] = "";
        }
        if (!("Account" in $$source)) {
            /**
             * @member
             * @type {AccountID}
             */
            this["Account"] = "";
        }
        if (!("Subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Subject"] = "";
        }
        if (!("From" in $$source)) {
            /**
             * @member
             * @type {Address[]}
             */
            this["From"] = [];
        }
        if (!("To" in $$source)) {
            /**
             * @member
             * @type {Address[]}
             */
            this["To"] = [];
        }
        if (!("Cc" in $$source)) {
            /**
             * @member
             * @type {Address[]}
             */
            this["Cc"] = [];
        }
        if (!("Bcc" in $$source)) {
            /**
             * @member
             * @type {Address[]}
             */
            this["Bcc"] = [];
        }
        if (!("Date" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Date"] = null;
        }
        if (!("Snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Snippet"] = "";
        }
        if (!("Flags" in $$source)) {
            /**
             * @member
             * @type {Flag[]}
             */
            this["Flags"] = [];
        }
        if (!("Labels" in $$source)) {
            /**
             * @member
             * @type {LabelID[]}
             */
            this["Labels"] = [];
        }
        if (!("HasAttachments" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["HasAttachments"] = false;
        }
        if (!("RFCMessageID" in $$source)) {
            /**
             * RFCMessageID is the RFC 5322 Message-ID header; References is the chain.
             * Used to construct correct reply/forward threading.
             * @member
             * @type {string}
             */
            this["RFCMessageID"] = "";
        }
        if (!("References" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["References"] = [];
        }
        if (!("BodyLoaded" in $$source)) {
            /**
             * BodyLoaded reports whether Parts are populated in the store.
             * @member
             * @type {boolean}
             */
            this["BodyLoaded"] = false;
        }
        if (!("Parts" in $$source)) {
            /**
             * @member
             * @type {Part[]}
             */
            this["Parts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField10_0 = $$createType3;
        const $$createField11_0 = $$createType4;
        const $$createField14_0 = $$createType5;
        const $$createField16_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("From" in $$parsedSource) {
            $$parsedSource["From"] = $$createField4_0($$parsedSource["From"]);
        }
        if ("To" in $$parsedSource) {
            $$parsedSource["To"] = $$createField5_0($$parsedSource["To"]);
        }
        if ("Cc" in $$parsedSource) {
            $$parsedSource["Cc"] = $$createField6_0($$parsedSource["Cc"]);
        }
        if ("Bcc" in $$parsedSource) {
            $$parsedSource["Bcc"] = $$createField7_0($$parsedSource["Bcc"]);
        }
        if ("Flags" in $$parsedSource) {
            $$parsedSource["Flags"] = $$createField10_0($$parsedSource["Flags"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField11_0($$parsedSource["Labels"]);
        }
        if ("References" in $$parsedSource) {
            $$parsedSource["References"] = $$createField14_0($$parsedSource["References"]);
        }
        if ("Parts" in $$parsedSource) {
            $$parsedSource["Parts"] = $$createField16_0($$parsedSource["Parts"]);
        }
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

/**
 * MessageID is the SDK-internal stable id for a message (typically the
 * RFC 5322 Message-ID, falling back to a synthesized id).
 * @typedef {string} MessageID
 */

/**
 * Outfile is an attachment to include in an Outgoing message.
 */
export class Outfile {
    /**
     * Creates a new Outfile instance.
     * @param {Partial<Outfile>} [$$source = {}] - The source object to create the Outfile.
     */
    constructor($$source = {}) {
        if (!("Filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Filename"] = "";
        }
        if (!("ContentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ContentType"] = "";
        }
        if (!("Content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Outfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Outfile}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Content" in $$parsedSource) {
            $$parsedSource["Content"] = $$createField2_0($$parsedSource["Content"]);
        }
        return new Outfile(/** @type {Partial<Outfile>} */($$parsedSource));
    }
}

/**
 * Outgoing is a message to be composed and sent.
 */
export class Outgoing {
    /**
     * Creates a new Outgoing instance.
     * @param {Partial<Outgoing>} [$$source = {}] - The source object to create the Outgoing.
     */
    constructor($$source = {}) {
        if (!("From" in $$source)) {
            /**
             * @member
             * @type {Address}
             */
            this["From"] = (new Address());
        }
        if (!("To" in $$source)) {
            /**
             * @member
             * @type {Address[]}
             */
            this["To"] = [];
        }
        if (!("Cc" in $$source)) {
            /**
             * @member
             * @type {Address[]}
             */
            this["Cc"] = [];
        }
        if (!("Bcc" in $$source)) {
            /**
             * @member
             * @type {Address[]}
             */
            this["Bcc"] = [];
        }
        if (!("Subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Subject"] = "";
        }
        if (!("Text" in $$source)) {
            /**
             * text/plain body
             * @member
             * @type {string}
             */
            this["Text"] = "";
        }
        if (!("HTML" in $$source)) {
            /**
             * optional text/html alternative
             * @member
             * @type {string}
             */
            this["HTML"] = "";
        }
        if (!("InReplyTo" in $$source)) {
            /**
             * Threading: when replying, set InReplyTo to the parent's Message-ID and
             * References to the full chain so clients thread the reply correctly.
             * @member
             * @type {string}
             */
            this["InReplyTo"] = "";
        }
        if (!("References" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["References"] = [];
        }
        if (!("Thread" in $$source)) {
            /**
             * Thread, if set, attaches the message to an existing provider thread.
             * @member
             * @type {ThreadID}
             */
            this["Thread"] = "";
        }
        if (!("Attachments" in $$source)) {
            /**
             * @member
             * @type {Outfile[]}
             */
            this["Attachments"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Outgoing instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Outgoing}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField8_0 = $$createType5;
        const $$createField10_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("From" in $$parsedSource) {
            $$parsedSource["From"] = $$createField0_0($$parsedSource["From"]);
        }
        if ("To" in $$parsedSource) {
            $$parsedSource["To"] = $$createField1_0($$parsedSource["To"]);
        }
        if ("Cc" in $$parsedSource) {
            $$parsedSource["Cc"] = $$createField2_0($$parsedSource["Cc"]);
        }
        if ("Bcc" in $$parsedSource) {
            $$parsedSource["Bcc"] = $$createField3_0($$parsedSource["Bcc"]);
        }
        if ("References" in $$parsedSource) {
            $$parsedSource["References"] = $$createField8_0($$parsedSource["References"]);
        }
        if ("Attachments" in $$parsedSource) {
            $$parsedSource["Attachments"] = $$createField10_0($$parsedSource["Attachments"]);
        }
        return new Outgoing(/** @type {Partial<Outgoing>} */($$parsedSource));
    }
}

/**
 * Part is a single MIME part of a message body.
 */
export class Part {
    /**
     * Creates a new Part instance.
     * @param {Partial<Part>} [$$source = {}] - The source object to create the Part.
     */
    constructor($$source = {}) {
        if (!("ContentType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ContentType"] = "";
        }
        if (!("Charset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Charset"] = "";
        }
        if (!("Disposition" in $$source)) {
            /**
             * inline | attachment
             * @member
             * @type {string}
             */
            this["Disposition"] = "";
        }
        if (!("Filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Filename"] = "";
        }
        if (!("Size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }
        if (!("Content" in $$source)) {
            /**
             * Content is populated only when loaded; large attachments are spooled to
             * the blob store and referenced by BlobRef instead.
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }
        if (!("BlobRef" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["BlobRef"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Part instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Part}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Content" in $$parsedSource) {
            $$parsedSource["Content"] = $$createField5_0($$parsedSource["Content"]);
        }
        return new Part(/** @type {Partial<Part>} */($$parsedSource));
    }
}

/**
 * Role tags well-known mailboxes so the UI can find them across providers.
 * @readonly
 * @enum {number}
 */
export const Role = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    RoleNone: 0,
    RoleInbox: 1,
    RoleSent: 2,
    RoleDrafts: 3,
    RoleTrash: 4,
    RoleSpam: 5,
    RoleArchive: 6,
};

/**
 * Snoozed records a message hidden from the inbox until Until.
 */
export class Snoozed {
    /**
     * Creates a new Snoozed instance.
     * @param {Partial<Snoozed>} [$$source = {}] - The source object to create the Snoozed.
     */
    constructor($$source = {}) {
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {MessageID}
             */
            this["Message"] = "";
        }
        if (!("Until" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Until"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snoozed instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snoozed}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snoozed(/** @type {Partial<Snoozed>} */($$parsedSource));
    }
}

/**
 * Thread is a conversation grouping.
 */
export class Thread {
    /**
     * Creates a new Thread instance.
     * @param {Partial<Thread>} [$$source = {}] - The source object to create the Thread.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {ThreadID}
             */
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            /**
             * @member
             * @type {AccountID}
             */
            this["Account"] = "";
        }
        if (!("Subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Subject"] = "";
        }
        if (!("Messages" in $$source)) {
            /**
             * @member
             * @type {MessageID[]}
             */
            this["Messages"] = [];
        }
        if (!("Last" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Last"] = null;
        }
        if (!("Unread" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Unread"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Thread instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Thread}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Messages" in $$parsedSource) {
            $$parsedSource["Messages"] = $$createField3_0($$parsedSource["Messages"]);
        }
        return new Thread(/** @type {Partial<Thread>} */($$parsedSource));
    }
}

/**
 * ThreadID groups messages into a conversation.
 * @typedef {string} ThreadID
 */

/**
 * ThreadListItem is a denormalized conversation-list row, purpose-built for a
 * UI inbox view: everything needed to render one row without loading messages.
 */
export class ThreadListItem {
    /**
     * Creates a new ThreadListItem instance.
     * @param {Partial<ThreadListItem>} [$$source = {}] - The source object to create the ThreadListItem.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {ThreadID}
             */
            this["ID"] = "";
        }
        if (!("Account" in $$source)) {
            /**
             * @member
             * @type {AccountID}
             */
            this["Account"] = "";
        }
        if (!("Subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Subject"] = "";
        }
        if (!("Last" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["Last"] = null;
        }
        if (!("Unread" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Unread"] = false;
        }
        if (!("Count" in $$source)) {
            /**
             * messages in the thread
             * @member
             * @type {number}
             */
            this["Count"] = 0;
        }
        if (!("LatestSender" in $$source)) {
            /**
             * From of the newest message
             * @member
             * @type {Address}
             */
            this["LatestSender"] = (new Address());
        }
        if (!("Participants" in $$source)) {
            /**
             * distinct senders across the thread, oldest first
             * @member
             * @type {Address[]}
             */
            this["Participants"] = [];
        }
        if (!("Snippet" in $$source)) {
            /**
             * newest message's snippet
             * @member
             * @type {string}
             */
            this["Snippet"] = "";
        }
        if (!("HasAttachments" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["HasAttachments"] = false;
        }
        if (!("Labels" in $$source)) {
            /**
             * union of labels across the thread
             * @member
             * @type {LabelID[]}
             */
            this["Labels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreadListItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThreadListItem}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("LatestSender" in $$parsedSource) {
            $$parsedSource["LatestSender"] = $$createField6_0($$parsedSource["LatestSender"]);
        }
        if ("Participants" in $$parsedSource) {
            $$parsedSource["Participants"] = $$createField7_0($$parsedSource["Participants"]);
        }
        if ("Labels" in $$parsedSource) {
            $$parsedSource["Labels"] = $$createField10_0($$parsedSource["Labels"]);
        }
        return new ThreadListItem(/** @type {Partial<ThreadListItem>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Outgoing.createFrom;
const $$createType1 = Address.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = Part.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Outfile.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
