// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Onboarding is a Wails service for adding, listing, and removing mail
 * accounts. Register it alongside the email Client so the frontend onboarding
 * flow can call these methods.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as email$0 from "../../email/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../model/models.js";

/**
 * AddAppPasswordAccount registers an IMAP/SMTP account authenticated with a
 * password or app password (e.g. a Gmail App Password). No OAuth, no browser.
 */
export function AddAppPasswordAccount(emailAddr: string, displayName: string, appPassword: string): $CancellablePromise<email$0.Account> {
    return $Call.ByID(534351019, emailAddr, displayName, appPassword).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddIMAPAccount registers a custom IMAP (incoming) + SMTP (outgoing) account
 * with an explicit server. Use this for providers that aren't in the built-in
 * endpoint map. Ports default to IMAP 993 (implicit TLS) and SMTP 587
 * (STARTTLS) when passed as 0; SMTP host defaults to the IMAP host.
 */
export function AddIMAPAccount(emailAddr: string, displayName: string, password: string, imapHost: string, imapPort: number, smtpHost: string, smtpPort: number): $CancellablePromise<email$0.Account> {
    return $Call.ByID(614760876, emailAddr, displayName, password, imapHost, imapPort, smtpHost, smtpPort).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListAccounts returns the configured accounts for the settings UI.
 */
export function ListAccounts(): $CancellablePromise<email$0.Account[]> {
    return $Call.ByID(3651192915).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RemoveAccount stops sync, forgets the account's local data, and deletes its
 * stored credential.
 */
export function RemoveAccount(id: email$0.AccountID): $CancellablePromise<void> {
    return $Call.ByID(1900057654, id);
}

// Private type creation functions
const $$createType0 = model$0.Account.createFrom;
const $$createType1 = $Create.Array($$createType0);
