// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
)

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, kind, email, name, imap_host, imap_port, smtp_host, smtp_port FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.Name,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, kind, email, name, imap_host, imap_port, smtp_host, smtp_port FROM accounts ORDER BY email
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Email,
			&i.Name,
			&i.ImapHost,
			&i.ImapPort,
			&i.SmtpHost,
			&i.SmtpPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (id, kind, email, name, imap_host, imap_port, smtp_host, smtp_port)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    email = excluded.email,
    name = excluded.name,
    imap_host = excluded.imap_host,
    imap_port = excluded.imap_port,
    smtp_host = excluded.smtp_host,
    smtp_port = excluded.smtp_port
`

type UpsertAccountParams struct {
	ID       string `json:"id"`
	Kind     int64  `json:"kind"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	ImapHost string `json:"imap_host"`
	ImapPort int64  `json:"imap_port"`
	SmtpHost string `json:"smtp_host"`
	SmtpPort int64  `json:"smtp_port"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount,
		arg.ID,
		arg.Kind,
		arg.Email,
		arg.Name,
		arg.ImapHost,
		arg.ImapPort,
		arg.SmtpHost,
		arg.SmtpPort,
	)
	return err
}
