// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contacts.sql

package db

import (
	"context"
)

const searchContacts = `-- name: SearchContacts :many
SELECT addr, name, last_seen, freq FROM contacts
WHERE account = ?1
  AND (addr LIKE ?2 OR name LIKE ?3)
ORDER BY freq DESC, last_seen DESC
LIMIT ?4
`

type SearchContactsParams struct {
	Account string `json:"account"`
	Addr    string `json:"addr"`
	Name    string `json:"name"`
	Limit   int64  `json:"limit"`
}

type SearchContactsRow struct {
	Addr     string `json:"addr"`
	Name     string `json:"name"`
	LastSeen int64  `json:"last_seen"`
	Freq     int64  `json:"freq"`
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]SearchContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchContacts,
		arg.Account,
		arg.Addr,
		arg.Name,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchContactsRow{}
	for rows.Next() {
		var i SearchContactsRow
		if err := rows.Scan(
			&i.Addr,
			&i.Name,
			&i.LastSeen,
			&i.Freq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (account, addr, name, last_seen, freq)
VALUES (?1, ?2, ?3, ?4, 1)
ON CONFLICT(account, addr) DO UPDATE SET
    last_seen = MAX(contacts.last_seen, excluded.last_seen),
    freq = contacts.freq + 1,
    -- Keep the display name from the most-recent message that carried one, so a
    -- later-but-older backfilled envelope doesn't clobber a fresher name.
    name = CASE
        WHEN excluded.name != '' AND excluded.last_seen >= contacts.last_seen THEN excluded.name
        ELSE contacts.name
    END
`

type UpsertContactParams struct {
	Account  string `json:"account"`
	Addr     string `json:"addr"`
	Name     string `json:"name"`
	LastSeen int64  `json:"last_seen"`
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact,
		arg.Account,
		arg.Addr,
		arg.Name,
		arg.LastSeen,
	)
	return err
}
