// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drafts.sql

package db

import (
	"context"
)

const deleteDraft = `-- name: DeleteDraft :exec
DELETE FROM drafts WHERE account = ? AND id = ?
`

type DeleteDraftParams struct {
	Account string `json:"account"`
	ID      string `json:"id"`
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) error {
	_, err := q.db.ExecContext(ctx, deleteDraft, arg.Account, arg.ID)
	return err
}

const getDraft = `-- name: GetDraft :one
SELECT id, account, payload, updated FROM drafts WHERE account = ? AND id = ?
`

type GetDraftParams struct {
	Account string `json:"account"`
	ID      string `json:"id"`
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (Draft, error) {
	row := q.db.QueryRowContext(ctx, getDraft, arg.Account, arg.ID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Payload,
		&i.Updated,
	)
	return i, err
}

const listDrafts = `-- name: ListDrafts :many
SELECT id, account, payload, updated FROM drafts WHERE account = ? ORDER BY updated DESC
`

func (q *Queries) ListDrafts(ctx context.Context, account string) ([]Draft, error) {
	rows, err := q.db.QueryContext(ctx, listDrafts, account)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Draft{}
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Payload,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDraft = `-- name: UpsertDraft :exec
INSERT INTO drafts (id, account, payload, updated)
VALUES (?, ?, ?, ?)
ON CONFLICT(account, id) DO UPDATE SET
    payload = excluded.payload,
    updated = excluded.updated
`

type UpsertDraftParams struct {
	ID      string `json:"id"`
	Account string `json:"account"`
	Payload string `json:"payload"`
	Updated int64  `json:"updated"`
}

func (q *Queries) UpsertDraft(ctx context.Context, arg UpsertDraftParams) error {
	_, err := q.db.ExecContext(ctx, upsertDraft,
		arg.ID,
		arg.Account,
		arg.Payload,
		arg.Updated,
	)
	return err
}
