// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: labels.sql

package db

import (
	"context"
)

const addLabel = `-- name: AddLabel :exec
INSERT INTO message_labels (account, message, label)
VALUES (?, ?, ?)
ON CONFLICT(account, message, label) DO NOTHING
`

type AddLabelParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
	Label   string `json:"label"`
}

func (q *Queries) AddLabel(ctx context.Context, arg AddLabelParams) error {
	_, err := q.db.ExecContext(ctx, addLabel, arg.Account, arg.Message, arg.Label)
	return err
}

const listMessageLabels = `-- name: ListMessageLabels :many
SELECT label FROM message_labels WHERE account = ? AND message = ?
`

type ListMessageLabelsParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
}

func (q *Queries) ListMessageLabels(ctx context.Context, arg ListMessageLabelsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMessageLabels, arg.Account, arg.Message)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLabel = `-- name: RemoveLabel :exec
DELETE FROM message_labels WHERE account = ? AND message = ? AND label = ?
`

type RemoveLabelParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
	Label   string `json:"label"`
}

func (q *Queries) RemoveLabel(ctx context.Context, arg RemoveLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeLabel, arg.Account, arg.Message, arg.Label)
	return err
}
