// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mailboxes.sql

package db

import (
	"context"
)

const deleteMailbox = `-- name: DeleteMailbox :exec
DELETE FROM mailboxes WHERE account = ? AND id = ?
`

type DeleteMailboxParams struct {
	Account string `json:"account"`
	ID      string `json:"id"`
}

func (q *Queries) DeleteMailbox(ctx context.Context, arg DeleteMailboxParams) error {
	_, err := q.db.ExecContext(ctx, deleteMailbox, arg.Account, arg.ID)
	return err
}

const listMailboxes = `-- name: ListMailboxes :many

SELECT id, account, name, path, role, unread, total, icon, icon_weight, icon_color
FROM mailboxes WHERE account = ? ORDER BY role, name
`

// UpsertMailbox (above) deliberately omits the icon columns from its ON CONFLICT
// update, so a user's chosen icon survives periodic topology sync.
func (q *Queries) ListMailboxes(ctx context.Context, account string) ([]Mailbox, error) {
	rows, err := q.db.QueryContext(ctx, listMailboxes, account)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mailbox{}
	for rows.Next() {
		var i Mailbox
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Name,
			&i.Path,
			&i.Role,
			&i.Unread,
			&i.Total,
			&i.Icon,
			&i.IconWeight,
			&i.IconColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMailboxIcon = `-- name: SetMailboxIcon :exec
UPDATE mailboxes SET icon = ?, icon_weight = ?, icon_color = ?
WHERE account = ? AND id = ?
`

type SetMailboxIconParams struct {
	Icon       string `json:"icon"`
	IconWeight string `json:"icon_weight"`
	IconColor  string `json:"icon_color"`
	Account    string `json:"account"`
	ID         string `json:"id"`
}

func (q *Queries) SetMailboxIcon(ctx context.Context, arg SetMailboxIconParams) error {
	_, err := q.db.ExecContext(ctx, setMailboxIcon,
		arg.Icon,
		arg.IconWeight,
		arg.IconColor,
		arg.Account,
		arg.ID,
	)
	return err
}

const upsertMailbox = `-- name: UpsertMailbox :exec
INSERT INTO mailboxes (id, account, name, path, role, unread, total)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account, id) DO UPDATE SET
    name = excluded.name,
    path = excluded.path,
    role = excluded.role,
    unread = excluded.unread,
    total = excluded.total
`

type UpsertMailboxParams struct {
	ID      string `json:"id"`
	Account string `json:"account"`
	Name    string `json:"name"`
	Path    string `json:"path"`
	Role    int64  `json:"role"`
	Unread  int64  `json:"unread"`
	Total   int64  `json:"total"`
}

func (q *Queries) UpsertMailbox(ctx context.Context, arg UpsertMailboxParams) error {
	_, err := q.db.ExecContext(ctx, upsertMailbox,
		arg.ID,
		arg.Account,
		arg.Name,
		arg.Path,
		arg.Role,
		arg.Unread,
		arg.Total,
	)
	return err
}
