// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
)

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE account = ? AND id = ?
`

type DeleteMessageParams struct {
	Account string `json:"account"`
	ID      string `json:"id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, arg.Account, arg.ID)
	return err
}

const getFlags = `-- name: GetFlags :one
SELECT flags FROM messages WHERE account = ? AND id = ?
`

type GetFlagsParams struct {
	Account string `json:"account"`
	ID      string `json:"id"`
}

func (q *Queries) GetFlags(ctx context.Context, arg GetFlagsParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getFlags, arg.Account, arg.ID)
	var flags string
	err := row.Scan(&flags)
	return flags, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, account, thread, subject, from_json, to_json, cc_json, bcc_json, date, snippet, flags, has_attachments, body_loaded, rfc_message_id, refs, category FROM messages WHERE account = ? AND id = ?
`

type GetMessageParams struct {
	Account string `json:"account"`
	ID      string `json:"id"`
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, arg.Account, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Thread,
		&i.Subject,
		&i.FromJson,
		&i.ToJson,
		&i.CcJson,
		&i.BccJson,
		&i.Date,
		&i.Snippet,
		&i.Flags,
		&i.HasAttachments,
		&i.BodyLoaded,
		&i.RfcMessageID,
		&i.Refs,
		&i.Category,
	)
	return i, err
}

const listMailboxMessages = `-- name: ListMailboxMessages :many
SELECT m.id, m.account, m.thread, m.subject, m.from_json, m.to_json, m.cc_json, m.bcc_json, m.date, m.snippet, m.flags, m.has_attachments, m.body_loaded, m.rfc_message_id, m.refs, m.category FROM messages m
JOIN message_labels l ON l.account = m.account AND l.message = m.id
WHERE m.account = ? AND l.label = ?
ORDER BY m.date DESC
LIMIT ?
`

type ListMailboxMessagesParams struct {
	Account string `json:"account"`
	Label   string `json:"label"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListMailboxMessages(ctx context.Context, arg ListMailboxMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMailboxMessages, arg.Account, arg.Label, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Thread,
			&i.Subject,
			&i.FromJson,
			&i.ToJson,
			&i.CcJson,
			&i.BccJson,
			&i.Date,
			&i.Snippet,
			&i.Flags,
			&i.HasAttachments,
			&i.BodyLoaded,
			&i.RfcMessageID,
			&i.Refs,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT id, account, thread, subject, from_json, to_json, cc_json, bcc_json, date, snippet, flags, has_attachments, body_loaded, rfc_message_id, refs, category FROM messages
WHERE account = ? AND thread = ?
ORDER BY date ASC
`

type ListThreadMessagesParams struct {
	Account string `json:"account"`
	Thread  string `json:"thread"`
}

func (q *Queries) ListThreadMessages(ctx context.Context, arg ListThreadMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listThreadMessages, arg.Account, arg.Thread)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Thread,
			&i.Subject,
			&i.FromJson,
			&i.ToJson,
			&i.CcJson,
			&i.BccJson,
			&i.Date,
			&i.Snippet,
			&i.Flags,
			&i.HasAttachments,
			&i.BodyLoaded,
			&i.RfcMessageID,
			&i.Refs,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBodyLoaded = `-- name: SetBodyLoaded :exec
UPDATE messages SET body_loaded = ? WHERE account = ? AND id = ?
`

type SetBodyLoadedParams struct {
	BodyLoaded int64  `json:"body_loaded"`
	Account    string `json:"account"`
	ID         string `json:"id"`
}

func (q *Queries) SetBodyLoaded(ctx context.Context, arg SetBodyLoadedParams) error {
	_, err := q.db.ExecContext(ctx, setBodyLoaded, arg.BodyLoaded, arg.Account, arg.ID)
	return err
}

const setFlags = `-- name: SetFlags :exec
UPDATE messages SET flags = ? WHERE account = ? AND id = ?
`

type SetFlagsParams struct {
	Flags   string `json:"flags"`
	Account string `json:"account"`
	ID      string `json:"id"`
}

func (q *Queries) SetFlags(ctx context.Context, arg SetFlagsParams) error {
	_, err := q.db.ExecContext(ctx, setFlags, arg.Flags, arg.Account, arg.ID)
	return err
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages (
    id, account, thread, subject,
    from_json, to_json, cc_json, bcc_json,
    date, snippet, category, flags, has_attachments, body_loaded,
    rfc_message_id, refs
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account, id) DO UPDATE SET
    thread = excluded.thread,
    subject = excluded.subject,
    from_json = excluded.from_json,
    to_json = excluded.to_json,
    cc_json = excluded.cc_json,
    bcc_json = excluded.bcc_json,
    date = excluded.date,
    snippet = excluded.snippet,
    category = excluded.category,
    flags = excluded.flags,
    has_attachments = excluded.has_attachments,
    body_loaded = excluded.body_loaded,
    rfc_message_id = excluded.rfc_message_id,
    refs = excluded.refs
`

type UpsertMessageParams struct {
	ID             string `json:"id"`
	Account        string `json:"account"`
	Thread         string `json:"thread"`
	Subject        string `json:"subject"`
	FromJson       string `json:"from_json"`
	ToJson         string `json:"to_json"`
	CcJson         string `json:"cc_json"`
	BccJson        string `json:"bcc_json"`
	Date           int64  `json:"date"`
	Snippet        string `json:"snippet"`
	Category       string `json:"category"`
	Flags          string `json:"flags"`
	HasAttachments int64  `json:"has_attachments"`
	BodyLoaded     int64  `json:"body_loaded"`
	RfcMessageID   string `json:"rfc_message_id"`
	Refs           string `json:"refs"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessage,
		arg.ID,
		arg.Account,
		arg.Thread,
		arg.Subject,
		arg.FromJson,
		arg.ToJson,
		arg.CcJson,
		arg.BccJson,
		arg.Date,
		arg.Snippet,
		arg.Category,
		arg.Flags,
		arg.HasAttachments,
		arg.BodyLoaded,
		arg.RfcMessageID,
		arg.Refs,
	)
	return err
}
