// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Account struct {
	ID       string `json:"id"`
	Kind     int64  `json:"kind"`
	Email    string `json:"email"`
	Name     string `json:"name"`
	ImapHost string `json:"imap_host"`
	ImapPort int64  `json:"imap_port"`
	SmtpHost string `json:"smtp_host"`
	SmtpPort int64  `json:"smtp_port"`
}

type DoneLog struct {
	Account string `json:"account"`
	Message string `json:"message"`
	At      int64  `json:"at"`
}

type Draft struct {
	ID      string `json:"id"`
	Account string `json:"account"`
	Payload string `json:"payload"`
	Updated int64  `json:"updated"`
}

type Mailbox struct {
	ID         string `json:"id"`
	Account    string `json:"account"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	Role       int64  `json:"role"`
	Unread     int64  `json:"unread"`
	Total      int64  `json:"total"`
	Icon       string `json:"icon"`
	IconWeight string `json:"icon_weight"`
	IconColor  string `json:"icon_color"`
}

type Message struct {
	ID             string `json:"id"`
	Account        string `json:"account"`
	Thread         string `json:"thread"`
	Subject        string `json:"subject"`
	FromJson       string `json:"from_json"`
	ToJson         string `json:"to_json"`
	CcJson         string `json:"cc_json"`
	BccJson        string `json:"bcc_json"`
	Date           int64  `json:"date"`
	Snippet        string `json:"snippet"`
	Flags          string `json:"flags"`
	HasAttachments int64  `json:"has_attachments"`
	BodyLoaded     int64  `json:"body_loaded"`
	RfcMessageID   string `json:"rfc_message_id"`
	Refs           string `json:"refs"`
	Category       string `json:"category"`
}

type MessageLabel struct {
	Account string `json:"account"`
	Message string `json:"message"`
	Label   string `json:"label"`
}

type MessagesFt struct {
	Subject string `json:"subject"`
	Sender  string `json:"sender"`
	Body    string `json:"body"`
}

type OpLog struct {
	ID       int64  `json:"id"`
	Account  string `json:"account"`
	Op       string `json:"op"`
	Payload  string `json:"payload"`
	Attempts int64  `json:"attempts"`
	NextAt   int64  `json:"next_at"`
	Created  int64  `json:"created"`
}

type Part struct {
	Account     string `json:"account"`
	Message     string `json:"message"`
	Seq         int64  `json:"seq"`
	ContentType string `json:"content_type"`
	Charset     string `json:"charset"`
	Disposition string `json:"disposition"`
	Filename    string `json:"filename"`
	Size        int64  `json:"size"`
	Content     []byte `json:"content"`
	BlobRef     string `json:"blob_ref"`
}

type Snooze struct {
	Account string `json:"account"`
	Message string `json:"message"`
	Until   int64  `json:"until"`
	Created int64  `json:"created"`
}

type SyncState struct {
	Account      string `json:"account"`
	Mailbox      string `json:"mailbox"`
	Cursor       []byte `json:"cursor"`
	Backfill     []byte `json:"backfill"`
	BackfillDone int64  `json:"backfill_done"`
}

type Thread struct {
	ID      string `json:"id"`
	Account string `json:"account"`
	Subject string `json:"subject"`
	Last    int64  `json:"last"`
	Unread  int64  `json:"unread"`
}
