// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: parts.sql

package db

import (
	"context"
)

const deleteParts = `-- name: DeleteParts :exec
DELETE FROM parts WHERE account = ? AND message = ?
`

type DeletePartsParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
}

func (q *Queries) DeleteParts(ctx context.Context, arg DeletePartsParams) error {
	_, err := q.db.ExecContext(ctx, deleteParts, arg.Account, arg.Message)
	return err
}

const distinctBlobRefs = `-- name: DistinctBlobRefs :many
SELECT DISTINCT blob_ref FROM parts WHERE blob_ref != ''
`

func (q *Queries) DistinctBlobRefs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctBlobRefs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blob_ref string
		if err := rows.Scan(&blob_ref); err != nil {
			return nil, err
		}
		items = append(items, blob_ref)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPart = `-- name: InsertPart :exec
INSERT INTO parts (
    account, message, seq, content_type, charset,
    disposition, filename, content_id, size, content, blob_ref, cached_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account, message, seq) DO UPDATE SET
    content_type = excluded.content_type,
    charset = excluded.charset,
    disposition = excluded.disposition,
    filename = excluded.filename,
    content_id = excluded.content_id,
    size = excluded.size,
    content = excluded.content,
    blob_ref = excluded.blob_ref,
    cached_at = excluded.cached_at
`

type InsertPartParams struct {
	Account     string `json:"account"`
	Message     string `json:"message"`
	Seq         int64  `json:"seq"`
	ContentType string `json:"content_type"`
	Charset     string `json:"charset"`
	Disposition string `json:"disposition"`
	Filename    string `json:"filename"`
	ContentID   string `json:"content_id"`
	Size        int64  `json:"size"`
	Content     []byte `json:"content"`
	BlobRef     string `json:"blob_ref"`
	CachedAt    int64  `json:"cached_at"`
}

func (q *Queries) InsertPart(ctx context.Context, arg InsertPartParams) error {
	_, err := q.db.ExecContext(ctx, insertPart,
		arg.Account,
		arg.Message,
		arg.Seq,
		arg.ContentType,
		arg.Charset,
		arg.Disposition,
		arg.Filename,
		arg.ContentID,
		arg.Size,
		arg.Content,
		arg.BlobRef,
		arg.CachedAt,
	)
	return err
}

const listParts = `-- name: ListParts :many
SELECT account, message, seq, content_type, charset, disposition, filename, size, content, blob_ref, cached_at, content_id FROM parts WHERE account = ? AND message = ? ORDER BY seq
`

type ListPartsParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
}

func (q *Queries) ListParts(ctx context.Context, arg ListPartsParams) ([]Part, error) {
	rows, err := q.db.QueryContext(ctx, listParts, arg.Account, arg.Message)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Part{}
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.Account,
			&i.Message,
			&i.Seq,
			&i.ContentType,
			&i.Charset,
			&i.Disposition,
			&i.Filename,
			&i.Size,
			&i.Content,
			&i.BlobRef,
			&i.CachedAt,
			&i.ContentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
