// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddLabel(ctx context.Context, arg AddLabelParams) error
	BumpOp(ctx context.Context, arg BumpOpParams) error
	ClearCursor(ctx context.Context, arg ClearCursorParams) error
	CountDoneSince(ctx context.Context, arg CountDoneSinceParams) (int64, error)
	DeleteAccount(ctx context.Context, id string) error
	DeleteDraft(ctx context.Context, arg DeleteDraftParams) error
	DeleteMailbox(ctx context.Context, arg DeleteMailboxParams) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteOp(ctx context.Context, id int64) error
	DeleteParts(ctx context.Context, arg DeletePartsParams) error
	DeleteSnooze(ctx context.Context, arg DeleteSnoozeParams) error
	DueSnoozes(ctx context.Context, arg DueSnoozesParams) ([]string, error)
	EnqueueOp(ctx context.Context, arg EnqueueOpParams) error
	GetAccount(ctx context.Context, id string) (Account, error)
	GetBackfill(ctx context.Context, arg GetBackfillParams) ([]byte, error)
	GetCursor(ctx context.Context, arg GetCursorParams) ([]byte, error)
	GetDraft(ctx context.Context, arg GetDraftParams) (Draft, error)
	GetFlags(ctx context.Context, arg GetFlagsParams) (string, error)
	GetMessage(ctx context.Context, arg GetMessageParams) (Message, error)
	InsertPart(ctx context.Context, arg InsertPartParams) error
	ListAccounts(ctx context.Context) ([]Account, error)
	ListDrafts(ctx context.Context, account string) ([]Draft, error)
	ListMailboxMessages(ctx context.Context, arg ListMailboxMessagesParams) ([]Message, error)
	ListMailboxes(ctx context.Context, account string) ([]Mailbox, error)
	ListMessageLabels(ctx context.Context, arg ListMessageLabelsParams) ([]string, error)
	ListParts(ctx context.Context, arg ListPartsParams) ([]Part, error)
	ListSnoozes(ctx context.Context, account string) ([]ListSnoozesRow, error)
	ListThreadMessages(ctx context.Context, arg ListThreadMessagesParams) ([]Message, error)
	ListThreads(ctx context.Context, arg ListThreadsParams) ([]Thread, error)
	ReadyOps(ctx context.Context, arg ReadyOpsParams) ([]OpLog, error)
	RecordDone(ctx context.Context, arg RecordDoneParams) error
	RemoveLabel(ctx context.Context, arg RemoveLabelParams) error
	SetBackfill(ctx context.Context, arg SetBackfillParams) error
	SetBodyLoaded(ctx context.Context, arg SetBodyLoadedParams) error
	SetCursor(ctx context.Context, arg SetCursorParams) error
	SetFlags(ctx context.Context, arg SetFlagsParams) error
	UpsertAccount(ctx context.Context, arg UpsertAccountParams) error
	UpsertDraft(ctx context.Context, arg UpsertDraftParams) error
	UpsertMailbox(ctx context.Context, arg UpsertMailboxParams) error
	UpsertMessage(ctx context.Context, arg UpsertMessageParams) error
	UpsertSnooze(ctx context.Context, arg UpsertSnoozeParams) error
	UpsertThread(ctx context.Context, arg UpsertThreadParams) error
}

var _ Querier = (*Queries)(nil)
