// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: snooze.sql

package db

import (
	"context"
)

const countDoneSince = `-- name: CountDoneSince :one
SELECT COUNT(*) FROM done_log WHERE account = ? AND at >= ?
`

type CountDoneSinceParams struct {
	Account string `json:"account"`
	At      int64  `json:"at"`
}

func (q *Queries) CountDoneSince(ctx context.Context, arg CountDoneSinceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDoneSince, arg.Account, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSnooze = `-- name: DeleteSnooze :exec
DELETE FROM snoozes WHERE account = ? AND message = ?
`

type DeleteSnoozeParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
}

func (q *Queries) DeleteSnooze(ctx context.Context, arg DeleteSnoozeParams) error {
	_, err := q.db.ExecContext(ctx, deleteSnooze, arg.Account, arg.Message)
	return err
}

const dueSnoozes = `-- name: DueSnoozes :many
SELECT message FROM snoozes WHERE account = ? AND until <= ? ORDER BY until
`

type DueSnoozesParams struct {
	Account string `json:"account"`
	Until   int64  `json:"until"`
}

func (q *Queries) DueSnoozes(ctx context.Context, arg DueSnoozesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, dueSnoozes, arg.Account, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnoozes = `-- name: ListSnoozes :many
SELECT message, until FROM snoozes WHERE account = ? ORDER BY until
`

type ListSnoozesRow struct {
	Message string `json:"message"`
	Until   int64  `json:"until"`
}

func (q *Queries) ListSnoozes(ctx context.Context, account string) ([]ListSnoozesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSnoozes, account)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnoozesRow{}
	for rows.Next() {
		var i ListSnoozesRow
		if err := rows.Scan(&i.Message, &i.Until); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDone = `-- name: RecordDone :exec
INSERT INTO done_log (account, message, at)
VALUES (?, ?, ?)
ON CONFLICT(account, message) DO UPDATE SET at = excluded.at
`

type RecordDoneParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
	At      int64  `json:"at"`
}

func (q *Queries) RecordDone(ctx context.Context, arg RecordDoneParams) error {
	_, err := q.db.ExecContext(ctx, recordDone, arg.Account, arg.Message, arg.At)
	return err
}

const upsertSnooze = `-- name: UpsertSnooze :exec
INSERT INTO snoozes (account, message, until, created)
VALUES (?, ?, ?, ?)
ON CONFLICT(account, message) DO UPDATE SET until = excluded.until
`

type UpsertSnoozeParams struct {
	Account string `json:"account"`
	Message string `json:"message"`
	Until   int64  `json:"until"`
	Created int64  `json:"created"`
}

func (q *Queries) UpsertSnooze(ctx context.Context, arg UpsertSnoozeParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnooze,
		arg.Account,
		arg.Message,
		arg.Until,
		arg.Created,
	)
	return err
}
