// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sync.sql

package db

import (
	"context"
)

const bumpOp = `-- name: BumpOp :exec
UPDATE op_log SET attempts = attempts + 1, next_at = ? WHERE id = ?
`

type BumpOpParams struct {
	NextAt int64 `json:"next_at"`
	ID     int64 `json:"id"`
}

func (q *Queries) BumpOp(ctx context.Context, arg BumpOpParams) error {
	_, err := q.db.ExecContext(ctx, bumpOp, arg.NextAt, arg.ID)
	return err
}

const cancelSendOp = `-- name: CancelSendOp :execrows
DELETE FROM op_log WHERE account = ? AND id = ? AND op = 'send'
`

type CancelSendOpParams struct {
	Account string `json:"account"`
	ID      int64  `json:"id"`
}

func (q *Queries) CancelSendOp(ctx context.Context, arg CancelSendOpParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelSendOp, arg.Account, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearCursor = `-- name: ClearCursor :exec
DELETE FROM sync_state WHERE account = ? AND mailbox = ?
`

type ClearCursorParams struct {
	Account string `json:"account"`
	Mailbox string `json:"mailbox"`
}

func (q *Queries) ClearCursor(ctx context.Context, arg ClearCursorParams) error {
	_, err := q.db.ExecContext(ctx, clearCursor, arg.Account, arg.Mailbox)
	return err
}

const deleteOp = `-- name: DeleteOp :exec
DELETE FROM op_log WHERE id = ?
`

func (q *Queries) DeleteOp(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOp, id)
	return err
}

const enqueueOp = `-- name: EnqueueOp :one
INSERT INTO op_log (account, op, payload, next_at, created)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type EnqueueOpParams struct {
	Account string `json:"account"`
	Op      string `json:"op"`
	Payload string `json:"payload"`
	NextAt  int64  `json:"next_at"`
	Created int64  `json:"created"`
}

func (q *Queries) EnqueueOp(ctx context.Context, arg EnqueueOpParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, enqueueOp,
		arg.Account,
		arg.Op,
		arg.Payload,
		arg.NextAt,
		arg.Created,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getBackfill = `-- name: GetBackfill :one
SELECT backfill FROM sync_state WHERE account = ? AND mailbox = ?
`

type GetBackfillParams struct {
	Account string `json:"account"`
	Mailbox string `json:"mailbox"`
}

func (q *Queries) GetBackfill(ctx context.Context, arg GetBackfillParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getBackfill, arg.Account, arg.Mailbox)
	var backfill []byte
	err := row.Scan(&backfill)
	return backfill, err
}

const getBackfillState = `-- name: GetBackfillState :one
SELECT backfill, backfill_done FROM sync_state WHERE account = ? AND mailbox = ?
`

type GetBackfillStateParams struct {
	Account string `json:"account"`
	Mailbox string `json:"mailbox"`
}

type GetBackfillStateRow struct {
	Backfill     []byte `json:"backfill"`
	BackfillDone int64  `json:"backfill_done"`
}

func (q *Queries) GetBackfillState(ctx context.Context, arg GetBackfillStateParams) (GetBackfillStateRow, error) {
	row := q.db.QueryRowContext(ctx, getBackfillState, arg.Account, arg.Mailbox)
	var i GetBackfillStateRow
	err := row.Scan(&i.Backfill, &i.BackfillDone)
	return i, err
}

const getCursor = `-- name: GetCursor :one
SELECT cursor FROM sync_state WHERE account = ? AND mailbox = ?
`

type GetCursorParams struct {
	Account string `json:"account"`
	Mailbox string `json:"mailbox"`
}

func (q *Queries) GetCursor(ctx context.Context, arg GetCursorParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getCursor, arg.Account, arg.Mailbox)
	var cursor []byte
	err := row.Scan(&cursor)
	return cursor, err
}

const markBackfillDone = `-- name: MarkBackfillDone :exec
INSERT INTO sync_state (account, mailbox, backfill, backfill_done)
VALUES (?, ?, NULL, 1)
ON CONFLICT(account, mailbox) DO UPDATE SET backfill = NULL, backfill_done = 1
`

type MarkBackfillDoneParams struct {
	Account string `json:"account"`
	Mailbox string `json:"mailbox"`
}

func (q *Queries) MarkBackfillDone(ctx context.Context, arg MarkBackfillDoneParams) error {
	_, err := q.db.ExecContext(ctx, markBackfillDone, arg.Account, arg.Mailbox)
	return err
}

const readyOps = `-- name: ReadyOps :many
SELECT id, account, op, payload, attempts, next_at, created
FROM op_log
WHERE account = ? AND next_at <= ?
ORDER BY id
LIMIT ?
`

type ReadyOpsParams struct {
	Account string `json:"account"`
	NextAt  int64  `json:"next_at"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ReadyOps(ctx context.Context, arg ReadyOpsParams) ([]OpLog, error) {
	rows, err := q.db.QueryContext(ctx, readyOps, arg.Account, arg.NextAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OpLog{}
	for rows.Next() {
		var i OpLog
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Op,
			&i.Payload,
			&i.Attempts,
			&i.NextAt,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackfill = `-- name: SetBackfill :exec
INSERT INTO sync_state (account, mailbox, backfill)
VALUES (?, ?, ?)
ON CONFLICT(account, mailbox) DO UPDATE SET backfill = excluded.backfill
`

type SetBackfillParams struct {
	Account  string `json:"account"`
	Mailbox  string `json:"mailbox"`
	Backfill []byte `json:"backfill"`
}

func (q *Queries) SetBackfill(ctx context.Context, arg SetBackfillParams) error {
	_, err := q.db.ExecContext(ctx, setBackfill, arg.Account, arg.Mailbox, arg.Backfill)
	return err
}

const setCursor = `-- name: SetCursor :exec
INSERT INTO sync_state (account, mailbox, cursor)
VALUES (?, ?, ?)
ON CONFLICT(account, mailbox) DO UPDATE SET cursor = excluded.cursor
`

type SetCursorParams struct {
	Account string `json:"account"`
	Mailbox string `json:"mailbox"`
	Cursor  []byte `json:"cursor"`
}

func (q *Queries) SetCursor(ctx context.Context, arg SetCursorParams) error {
	_, err := q.db.ExecContext(ctx, setCursor, arg.Account, arg.Mailbox, arg.Cursor)
	return err
}
