// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: threads.sql

package db

import (
	"context"
)

const listThreads = `-- name: ListThreads :many
SELECT id, account, subject, last, unread
FROM threads WHERE account = ?
ORDER BY last DESC
LIMIT ?
`

type ListThreadsParams struct {
	Account string `json:"account"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListThreads(ctx context.Context, arg ListThreadsParams) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreads, arg.Account, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Thread{}
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Subject,
			&i.Last,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertThread = `-- name: UpsertThread :exec
INSERT INTO threads (id, account, subject, last, unread)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(account, id) DO UPDATE SET
    subject = CASE WHEN threads.subject = '' THEN excluded.subject ELSE threads.subject END,
    last    = MAX(threads.last, excluded.last),
    unread  = MAX(threads.unread, excluded.unread)
`

type UpsertThreadParams struct {
	ID      string `json:"id"`
	Account string `json:"account"`
	Subject string `json:"subject"`
	Last    int64  `json:"last"`
	Unread  int64  `json:"unread"`
}

func (q *Queries) UpsertThread(ctx context.Context, arg UpsertThreadParams) error {
	_, err := q.db.ExecContext(ctx, upsertThread,
		arg.ID,
		arg.Account,
		arg.Subject,
		arg.Last,
		arg.Unread,
	)
	return err
}
