// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncSettings is the thin Wails service that exposes runtime sync controls to
 * the frontend, keeping App's other methods off the binding surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notify$0 from "./notify/models.js";

/**
 * NotifyPrefs reports the current notification preferences.
 */
export function NotifyPrefs(): $CancellablePromise<notify$0.Prefs> {
    return $Call.ByID(1232258931).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PollIntervalSeconds reports the current background poll interval, in seconds.
 */
export function PollIntervalSeconds(): $CancellablePromise<number> {
    return $Call.ByID(1068183743);
}

/**
 * SetNotifyPrefs pushes the user's notification preferences to the backend; the
 * new-mail handler consults them before raising a desktop notification.
 */
export function SetNotifyPrefs(prefs: notify$0.Prefs): $CancellablePromise<void> {
    return $Call.ByID(414820467, prefs);
}

/**
 * SetPollInterval changes the background poll interval (seconds) and restarts
 * the sync loops. Values below the minimum are clamped server-side.
 */
export function SetPollInterval(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(1973661226, seconds);
}

// Private type creation functions
const $$createType0 = notify$0.Prefs.createFrom;
